import type { Metadata } from 'next';
import { inter } from './fonts';
import './globals.css';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
			</head>
			<body className={`${inter.className} antialiased`}>
				<ThemeProvider enableColorScheme={false}>{children}</ThemeProvider>
			</body>
		</html>
	);
}
